version: 2

jobs:
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt update
      # <https://stackoverflow.com/a/44333806/353337>
      - run: DEBIAN_FRONTEND=noninteractive apt install tzdata
      - run: apt install -y ruby
      - run: gem install awesome_bot
      - checkout
      - run: awesome_bot ~/work/README.md
