version: 2

jobs:
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt update
      - run: apt install -y npm git
      - run: npm install --global awesome-lint
      - run: awesome-lint ~/work/README.md
      - run: apt install -y ruby
      - run: gem install awesome_bot
      - run: awesome_bot --white-list https://awesome.re,https://portal.nersc.gov/project/sparse/superlu/ ~/work/README.md
