name: ci

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # "License was not detected by GitHub"
    # - run: sudo npm install --global awesome-lint
    # - run: awesome-lint README.md
    - run: sudo apt install -y ruby
    - run: sudo gem install awesome_bot
    # Allow redirect for awesome.re
    - run: awesome_bot --white-list https://awesome.re,https://portal.nersc.gov/project/sparse/superlu/ README.md
